export const CATEGORIES = [
  {
    id: 'fiction',
    name: 'Fiction',
    subcategories: [
      { id: 'sci-fi', name: 'Science Fiction' },
      { id: 'fantasy', name: 'Fantasy' },
      { id: 'mystery', name: 'Mystery & Thriller' },
      { id: 'romance', name: 'Romance' },
    ],
  },
  {
    id: 'non-fiction',
    name: 'Non-Fiction',
    subcategories: [
      { id: 'biography', name: 'Biography' },
      { id: 'history', name: 'History' },
      { id: 'science', name: 'Science' },
      { id: 'self-help', name: 'Self Help' },
    ],
  },
  {
    id: 'tech',
    name: 'Technology',
    subcategories: [
      { id: 'programming', name: 'Programming' },
      { id: 'ai', name: 'Artificial Intelligence' },
    ],
  },
];

export const FEATURED_AUTHOR = {
  id: 'a1',
  name: 'Elena Vance',
  imageUrl: 'https://picsum.photos/200/200?random=100',
  bio: 'Award-winning novelist known for intricate world-building and compelling character studies in modern science fiction.',
  notableWorks: ['The Starlight Echo', 'Void Walkers', 'Chronicles of Sol'],
};

export const MOCK_BOOKS = [
  {
    id: '1',
    title: 'The Starlight Echo',
    author: 'Elena Vance',
    coverUrl: 'https://picsum.photos/300/450?random=1',
    price: 24.99,
    rating: 4.8,
    reviewCount: 3420,
    isBestSeller: true,
    category: 'Science Fiction',
    description: 'A journey through the cosmos to find the last signal of humanity.',
  },
  {
    id: '2',
    title: 'Algorithms of Life',
    author: 'Dr. Alan Reave',
    coverUrl: 'https://picsum.photos/300/450?random=2',
    price: 39.50,
    rating: 4.5,
    reviewCount: 120,
    isBestSeller: false,
    category: 'Science',
    description: 'Understanding the biological patterns that define our existence.',
  },
  {
    id: '3',
    title: 'The Silent Forest',
    author: 'Sarah Jenkins',
    coverUrl: 'https://picsum.photos/300/450?random=3',
    price: 18.99,
    rating: 4.2,
    reviewCount: 890,
    isBestSeller: true,
    category: 'Mystery & Thriller',
    description: 'A detective returns to her hometown to solve a cold case.',
  },
  {
    id: '4',
    title: 'Coding for Humans',
    author: 'Marcus Chen',
    coverUrl: 'https://picsum.photos/300/450?random=4',
    price: 29.99,
    rating: 4.9,
    reviewCount: 560,
    isBestSeller: true,
    category: 'Programming',
    description: 'An approachable guide to software engineering principles.',
  },
  {
    id: '5',
    title: 'Empire of Sand',
    author: 'J.D. Thompson',
    coverUrl: 'https://picsum.photos/300/450?random=5',
    price: 22.50,
    rating: 3.9,
    reviewCount: 430,
    isBestSeller: false,
    category: 'Fantasy',
    description: 'An epic tale of magic, betrayal, and kingdoms lost to time.',
  },
  {
    id: '6',
    title: 'Mind over Matter',
    author: 'Lisa Ray',
    coverUrl: 'https://picsum.photos/300/450?random=6',
    price: 15.99,
    rating: 4.6,
    reviewCount: 2100,
    isBestSeller: false,
    category: 'Self Help',
    description: 'Techniques to master your focus in a distracted world.',
  },
  {
    id: '7',
    title: 'Neural Networks 101',
    author: 'James Bot',
    coverUrl: 'https://picsum.photos/300/450?random=7',
    price: 45.00,
    rating: 4.7,
    reviewCount: 150,
    isBestSeller: false,
    category: 'Artificial Intelligence',
    description: 'Deep learning explained simply for beginners.',
  },
  {
    id: '8',
    title: 'The Last Queen',
    author: 'Victoria Hale',
    coverUrl: 'https://picsum.photos/300/450?random=8',
    price: 21.00,
    rating: 4.4,
    reviewCount: 980,
    isBestSeller: true,
    category: 'History',
    description: 'A biographical look at the final days of the monarchy.',
  },
];
